import Head from 'next/head'
import { Inter } from '@next/font/google'
import Link from 'next/link'
import NavBar from '@/component/navbar'
import Carousel from '@/component/Carousel'
import Tree from '@/component/tree'
import { InView } from 'react-intersection-observer';
import { useState } from 'react'
import banner1 from "../../public/banner.jpg"
import banner2 from "../../public/banner_second.jpg"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [isVisible,setVisible]=useState(false)
  const [isVisible1,setVisible1]=useState(false)

  return (
    <>
      <Head>
        <title>Xadventure</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='landing'>
        <video muted loop autoPlay playsInline preload="auto" >
          <source src='./test.mp4' />
        </video>
        <h1>Discover the world like never before.</h1>
        <button><Link href="./#offer">See our offer</Link><img className="plane" src='./plane.svg' /></button>
      </div>
      <NavBar />
      <div className='presentation'>
        <div className='card'>

        <InView as="h1" onChange={(inView)=>setVisible(inView)} className={isVisible?'subline active':"subline"}>What are we about ?</InView>
        <p>Welcome to our adventure agency! We are a team of passionate explorers who believe that life is meant to be lived to the fullest. Our goal is to provide you with unforgettable experiences that will leave you with lifelong memories.<br/><br/>At our agency, we believe in responsible tourism and sustainable travel practices. We strive to minimize our impact on the environment and support local communities in the areas we visit. We want to ensure that our adventures are not only thrilling and fun but also ethical and sustainable.<br/><br/>

Whether you are planning an adventure with family, friends, or solo, we&apos;re here to make it happen. So come and join us, let&apos;s embark on an adventure of a lifetime!</p>
        </div>
        
      </div>
      <div className="banner first" style={{backgroundImage: `url(${banner1.src})`}}></div>
      <div id="feedback" className='feedBack'>
      <InView as="h1" onChange={(inView)=>setVisible1(inView)} className={isVisible1?'subline active':"subline"}>They talk of us better than ourselves.</InView>
        <Carousel />
      </div>
      <div id="offer" style={{backgroundImage: `url(${banner2.src})`}} className="banner second" ></div>
      <div  className='feedBack'>
      <InView as="h1" onChange={(inView)=>setVisible1(inView)} className={isVisible1?'subline active':"subline"}>What do we offer ?</InView>
      <p><br/>We provide an unforgettable custom made adventure, especially created for you.<br/><br/>Our objective is to make you live something new that you can handle even we also here to push  your limits further. After this experience we want you to be a better version of yourself: With a better mental and a new point of view. <br /><br /> <em>THE ONLY LIMITS KNOWS ARE THE ONE YOU SET FOR YOUSERLF </em> , myself. </p>
       
      </div>
      <Tree />
      <div id="contact" className='feedBack'>
      <InView as="h1" onChange={(inView)=>setVisible1(inView)} className={isVisible1?'subline active':"subline"}>Contact Us</InView>
     
       <form action="https://formsubmit.co/durville.maxime.pro@gmail.com"  method="POST">
          <input type="hidden" name="_captcha" value="false"></input>
          <input type="hidden" name="_next" value="http:/localhost:3000/thankyou"></input>
          <div className="containerInput email">
            <label htmlFor="email">Adresse Email*</label>
            <input type="email" name="email"  required/>
          </div>
          
          <div className="containerInput firstName">
            <label htmlFor="firstName">Nom</label>
            <input type="text" name="firstName"  required/>
          </div>
          
          <div className="containerInput lastName">
            <label htmlFor="lastName">Prénom*</label>
            <input type="text" name="lastName" required/>
          </div>

          <div className="containerInput phone">
            <label  htmlFor="phone">Numéro de Téléphone</label>
            <input type="tel" name="phone" />
          </div>

          <div className="containerInput message">
            <label  htmlFor="message">Votre Projet*</label>
            <textarea type="text" name="message" required/>
          </div>
          <div className="containerInput message">
            <label  htmlFor="last">Durée de votre séjour</label>
            <textarea type="text" name="last" required/>
          </div>
          <button type="submit">Envoyer</button>
        </form>
      </div>
    </>
  )
}
